# Generated by Django 3.1.6 on 2021-08-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List_vacant',
        ),
        migrations.DeleteModel(
            name='Soldier',
        ),
        migrations.DeleteModel(
            name='Vacant',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
