# Generated by Django 3.1.6 on 2021-08-21 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffing', '0003_list_vacant_soldier_vacant_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Орган управления')),
                ('all_state', models.CharField(blank=True, max_length=100, verbose_name='Всего по штату')),
                ('all_nal', models.CharField(blank=True, max_length=100, verbose_name='Всего в наличии')),
                ('all_nekomplekt', models.CharField(blank=True, max_length=100, verbose_name='Всего некомплект')),
                ('all_percent', models.CharField(blank=True, max_length=100, verbose_name='Всего % укомплектованности')),
                ('off_state', models.CharField(blank=True, max_length=100, verbose_name='Офицеры по штату')),
                ('off_nal', models.CharField(blank=True, max_length=100, verbose_name='Офицеры в наличии')),
                ('off_nekomplekt', models.CharField(blank=True, max_length=100, verbose_name='Офицеры некомплект')),
                ('off_percent', models.CharField(blank=True, max_length=100, verbose_name='Офицеры % укомплектованности')),
                ('prap_state', models.CharField(blank=True, max_length=100, verbose_name='Прапорщики по штату')),
                ('prap_nal', models.CharField(blank=True, max_length=100, verbose_name='Прапорщики в наличии')),
                ('prap_nekomplekt', models.CharField(blank=True, max_length=100, verbose_name='Прапорщики некомплект')),
                ('prap_percent', models.CharField(blank=True, max_length=100, verbose_name='Прапорщики % укомплектованности')),
                ('kontrakt_state', models.CharField(blank=True, max_length=200, verbose_name='Военнослужащие по контракту на должностях солдат и сержантов по штату')),
                ('kontrakt_nal', models.CharField(blank=True, max_length=200, verbose_name='Военнослужащие по контракту на должностях солдат и сержантов в наличии')),
                ('kontrakt_nekomplekt', models.CharField(blank=True, max_length=200, verbose_name='Военнослужащие по контракту на должностях солдат и сержантов некомплект')),
                ('kontrakt_percent', models.CharField(blank=True, max_length=200, verbose_name='Военнослужащие по контракту на должностях солдат и сержантов % укомплектованности')),
                ('srok_state', models.CharField(blank=True, max_length=100, verbose_name='Военнослужащие срочной службы по штату')),
                ('srok_nal', models.CharField(blank=True, max_length=100, verbose_name='Военнослужащие срочной службы в наличии')),
                ('srok_nekomplekt', models.CharField(blank=True, max_length=100, verbose_name='Военнослужащие срочной службы некомплект')),
                ('srok_percent', models.CharField(blank=True, max_length=100, verbose_name='Военнослужащие срочной службы % укомплектованности')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_all_staff', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='members_all_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ИТОГО за ЦО',
                'verbose_name_plural': 'ИТОГО за ЦО',
            },
        ),
    ]
