# Generated by Django 3.1.6 on 2021-08-25 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffing', '0004_all_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacant',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_vacant', to=settings.AUTH_USER_MODEL),
        ),
    ]
