# Generated by Django 3.1.6 on 2021-08-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0005_auto_20210826_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacant',
            name='author',
        ),
    ]
