# Generated by Django 3.1.6 on 2021-08-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0006_remove_vacant_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacant',
        ),
    ]
