# Generated by Django 3.1.6 on 2021-08-25 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffing', '0007_delete_vacant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.CharField(blank=True, max_length=100, verbose_name='№ п/п')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Орган управления (№ в/ч)')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Место дислокации')),
                ('vacant_position', models.CharField(blank=True, max_length=100, verbose_name='Вакантная должность (наименование)')),
                ('rank_state', models.CharField(blank=True, max_length=100, verbose_name='В/зв (специальное) по штату')),
                ('tariff', models.CharField(blank=True, max_length=100, verbose_name='Тарифный разряд')),
                ('vus', models.CharField(blank=True, max_length=100, verbose_name='ВУС')),
                ('date_vacant', models.CharField(blank=True, max_length=100, verbose_name='С какой даты должность вакантна')),
                ('candidate', models.CharField(blank=True, max_length=50, verbose_name='Кто подобран (в/зв, спец., призывается), Ф.И.О.)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_vacant', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='members_vacant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Перечень вакантных должностей',
                'verbose_name_plural': 'Перечень вакантных должностей',
            },
        ),
    ]
