# Generated by Django 3.1.6 on 2021-08-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0009_soldier_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
    ]
