# Generated by Django 3.1.6 on 2021-08-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0015_auto_20210831_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Орган управления'),
        ),
    ]
